# Generated by Django 3.2.9 on 2022-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('regNo', models.CharField(max_length=9)),
                ('Block', models.CharField(max_length=2)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('roomNo', models.IntegerField()),
                ('phoneNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='OffersCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('priceForEach', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending')], max_length=1)),
                ('Restaurant', models.CharField(default='default store', max_length=20)),
                ('received', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(default='Outlet', max_length=30)),
                ('item', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=None)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Store Menu',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=30)),
                ('storeDesc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
